//Rented cars for a period sorted by customer id:
SELECT CLIENT.NAME AS client,BRAND,MODEL,EMPLOYEES.NAME AS employee,RENT_DATE,DAILY_PRICE*DAYS AS total FROM RENT R
JOIN CLIENT ON CLIENT.ID_CLIENT=R.CLIENT_ID
JOIN CAR ON CAR.ID_CAR=R.CAR_ID
JOIN MODEL M ON M.id_model=CAR.MODEL_ID
JOIN BRAND ON BRAND.id_brand=M.BRAND_ID
JOIN EMPLOYEES ON EMPLOYEES.ID_EMPLOYEE=R.EMPLOYEES_ID
WHERE RENT_DATE BETWEEN '&Начална_дата' and '&Крайна_дата'
ORDER BY CLIENT_ID;
