//Hired cars by employee, sorted by type and date:
SELECT  CLIENT.ID_CLIENT,EMPLOYEES.NAME AS emplyoee,TYPE,BRAND,MODEL,COLOR,TRAVELED,CLIENT.NAME AS client,RENT_DATE 
FROM CAR C
JOIN RENT ON RENT.CAR_ID=C.ID_CAR
JOIN TYPE ON TYPE.ID_TYPE=C.TYPE_ID
JOIN COLOR ON COLOR.ID_COLOR=C.COLOR_ID
JOIN MODEL M ON M.id_model=C.MODEL_ID
JOIN BRAND ON BRAND.id_brand=M.BRAND_ID
JOIN CLIENT ON CLIENT.ID_CLIENT=RENT.CLIENT_ID
JOIN EMPLOYEES ON EMPLOYEES.ID_EMPLOYEE=RENT.EMPLOYEES_ID
WHERE EMPLOYEES_ID LIKE '&employee_id'
ORDER BY C.TYPE_ID,RENT_date;
