//The last 10 loans, sorted by number of days of loan:
SELECT * FROM 
(SELECT CLIENT.NAME AS client,EMPLOYEES.NAME AS employee,POSITION,BRAND,MODEL,RENT_DATE,DAYS,DAILY_PRICE*DAYS AS total FROM RENT R
JOIN CLIENT ON CLIENT.ID_CLIENT=R.CLIENT_ID
JOIN CAR ON CAR.ID_CAR=R.CAR_ID
JOIN MODEL M ON M.id_model=CAR.MODEL_ID
JOIN BRAND ON BRAND.id_brand=M.BRAND_ID
JOIN EMPLOYEES ON EMPLOYEES.ID_EMPLOYEE=R.EMPLOYEES_ID
JOIN POSITION ON POSITION.ID_POSITION=EMPLOYEES.POSITION_ID
ORDER BY DAYS DESC)
WHERE ROWNUM<=10;
