CREATE TABLE type (
    id_type INTEGER NOT NULL,
    type    VARCHAR2(20),
    PRIMARY KEY ( id_type )
);

INSERT INTO TYPE(ID_TYPE,TYPE) VALUES (1,'Седан');
INSERT INTO TYPE(ID_TYPE,TYPE) VALUES (2,'Хечбек');
INSERT INTO TYPE(ID_TYPE,TYPE) VALUES (3,'Комби');
INSERT INTO TYPE(ID_TYPE,TYPE) VALUES (4,'Джип');
INSERT INTO TYPE(ID_TYPE,TYPE) VALUES (5,'Камион');

UPDATE TYPE
SET type='Автобус' 
WHERE ID_TYPE=5;

DELETE FROM TYPE WHERE ID_TYPE=5;

